name: smart_farm
description: A Flutter app for monitoring and controlling an Arduino-powered Smart Farm.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.63.0
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - web/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: web/fonts/Poppins-Regular.ttf
        - asset: web/fonts/Poppins-Bold.ttf
          weight: 700
